# Generated by Django 2.0 on 2018-04-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tz_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='height',
        ),
        migrations.RemoveField(
            model_name='resolution',
            name='width',
        ),
    ]
